import type { ToolboxItem } from './types'

export const CORE_TOOLBOX_ITEMS: ToolboxItem[] = [
  {
    id: 'decision-engine',
    name: 'Decision Engine',
    category: 'Decision',
    description: '單一事實驅動決策入口，輸出 machine-readable 報告。',
    location: 'scripts/decision-engine.py',
    commands: ['python3 scripts/decision-engine.py', 'python3 scripts/decision-engine.py --execute'],
    tags: ['pdca', 'decision-loop', 'report'],
    readiness: 'Ready',
    useCase: '當你要讓系統依據現況自動決定下一步任務時使用。',
    startup: 'cd /Users/ryan/meta-agent && python3 scripts/decision-engine.py',
    verify: '會更新 machine-readable 決策報告（decision-loop-last）。',
    blocker: '狀態檔缺失或過舊會讓決策偏保守。',
  },
  {
    id: 'health-check',
    name: 'Health Check',
    category: 'Validation',
    description: '系統健康狀態檢查，確認關鍵流程可用。',
    location: 'scripts/health_check.py',
    commands: ['python3 scripts/health_check.py'],
    tags: ['health', 'status'],
    readiness: 'Ready',
    useCase: '開工前或異常時，先快速確認核心系統健康。',
    startup: 'cd /Users/ryan/meta-agent && python3 scripts/health_check.py',
    verify: '主要檢查項 pass，且輸出可讀狀態結果。',
    blocker: '服務未啟動、port 衝突、env 不完整。',
  },
  {
    id: 'e2e',
    name: 'E2E Test',
    category: 'Validation',
    description: '端對端測試，驗證主流程完整性。',
    location: 'scripts/e2e_test.py',
    commands: ['python3 scripts/e2e_test.py'],
    tags: ['e2e', 'qa'],
    readiness: 'Manual Setup',
    useCase: '重大改動後，驗證完整端到端流程是否可用。',
    startup: 'cd /Users/ryan/meta-agent && python3 scripts/e2e_test.py',
    verify: 'E2E 全流程通過，且有可追溯結果。',
    blocker: '依賴服務未起來或測試資料不一致。',
  },
  {
    id: 'truth-xval',
    name: 'Truth Cross-Validation',
    category: 'Validation',
    description: '交叉查核事實一致性，失敗修復流程核心工具。',
    location: 'scripts/truth-xval.py',
    commands: ['python3 scripts/truth-xval.py'],
    tags: ['truth', 'xval', 'consistency'],
    readiness: 'Ready',
    useCase: '當 health/e2e 失敗或結果互相矛盾時做交叉查核。',
    startup: 'cd /Users/ryan/meta-agent && python3 scripts/truth-xval.py',
    verify: '可指出事實來源不一致的點與衝突面。',
    blocker: '來源資料格式不一致、舊狀態殘留。',
  },
  {
    id: 'memory-mcp',
    name: 'Memory MCP Server',
    category: 'Memory',
    description: '本地記憶查詢與寫入伺服器，供多代理共用。',
    location: 'tools/memory-mcp/server.py',
    commands: ['python3 tools/memory-mcp/server.py'],
    tags: ['mcp', 'memory', 'lightrag'],
    readiness: 'Manual Setup',
    useCase: '多代理共享記憶查詢/寫入時啟動。',
    startup: 'cd /Users/ryan/meta-agent && python3 tools/memory-mcp/server.py',
    verify: '服務可回應 query/ingest 類請求。',
    blocker: 'LightRAG 或相關設定未就緒。',
  },
  {
    id: 'agent-status',
    name: 'Agent SSH Status',
    category: 'SSH Gateway',
    description: '查看 gateway 開關、失敗 job 與基礎狀態。',
    location: 'tools/agent-ssh-gateway/host/bin/agent-status',
    commands: ['tools/agent-ssh-gateway/host/bin/agent-status'],
    tags: ['ssh', 'status', 'gateway'],
    readiness: 'Manual Setup',
    useCase: '檢查受控 SSH gateway 當前狀態與異常。',
    startup: 'cd /Users/ryan/meta-agent && tools/agent-ssh-gateway/host/bin/agent-status',
    verify: '可讀到 on/off、failed jobs、基本運行狀態。',
    blocker: 'host 端尚未完成部署或權限不足。',
  },
  {
    id: 'agent-switch',
    name: 'Agent SSH Switch',
    category: 'SSH Gateway',
    description: '快速開關受控 SSH 執行通道。',
    location: 'tools/agent-ssh-gateway/host/bin/agent-switch',
    commands: ['tools/agent-ssh-gateway/host/bin/agent-switch on', 'tools/agent-ssh-gateway/host/bin/agent-switch off'],
    tags: ['ssh', 'safety', 'on-off'],
    readiness: 'Manual Setup',
    useCase: '批次遠端操作前開啟，異常時快速關閉。',
    startup: 'cd /Users/ryan/meta-agent && tools/agent-ssh-gateway/host/bin/agent-switch on',
    verify: 'status 顯示狀態切換成功。',
    blocker: 'enabled flag/路徑/權限未配置。',
  },
  {
    id: 'novel-server',
    name: 'Novel Analyzer Web',
    category: 'Novel Analyzer',
    description: '局心欲變分析系統 Web 入口。',
    location: 'tools/novel-framework-analyzer/server.py',
    commands: ['cd tools/novel-framework-analyzer && python3 server.py'],
    tags: ['novel', 'framework', 'fastapi'],
    readiness: 'Ready',
    useCase: '啟動小說局心欲變分析的 Web 入口。',
    startup: 'cd /Users/ryan/meta-agent/tools/novel-framework-analyzer && python3 server.py',
    verify: '可開啟 localhost:8765 並使用分析 API。',
    blocker: '資料庫或套件依賴未就緒。',
  },
  {
    id: 'novel-batch',
    name: 'Novel Batch Analyze',
    category: 'Novel Analyzer',
    description: '批次分析章節場景，寫入資料庫。',
    location: 'tools/novel-framework-analyzer/scripts/batch_analyze.py',
    commands: ['python3 tools/novel-framework-analyzer/scripts/batch_analyze.py'],
    tags: ['novel', 'batch', 'scene'],
    readiness: 'Manual Setup',
    useCase: '新文本匯入後，批次產生場景分析卡。',
    startup: 'cd /Users/ryan/meta-agent && python3 tools/novel-framework-analyzer/scripts/batch_analyze.py',
    verify: '資料庫 scene cards 有新增，summary 變化。',
    blocker: '文本格式或模型設定不符合。',
  },
  {
    id: 'toolbox-console-dev',
    name: 'Toolbox Console Dev',
    category: 'Toolbox',
    description: '目前這個 React 可視化工具箱專案的開發模式。',
    location: 'scripts/toolbox-console/package.json',
    commands: ['npm run dev', 'npm run build', 'npm run lint'],
    tags: ['react', 'vite', 'toolbox'],
    readiness: 'Ready',
    useCase: '維護目前這個可視化工具箱前端。',
    startup: 'cd /Users/ryan/meta-agent/scripts/toolbox-console && npm run dev',
    verify: '本機頁面可開、卡片可互動、指令可複製。',
    blocker: 'Node 版本或依賴不相容。',
  },
  {
    id: 'douyin-sender',
    name: 'Douyin Sender UI',
    category: 'Toolbox',
    description: '桌面抖音投遞器，將影片連結送入 n8n 工作流。',
    location: '/Users/ryan/Desktop/douyin_sender.py',
    commands: ['python3 /Users/ryan/Desktop/douyin_sender.py'],
    tags: ['douyin', 'tiktok', 'transcription', 'n8n'],
    readiness: 'Needs Service',
    useCase: '把抖音/TikTok 連結快速投遞到 n8n 工作流。',
    startup: 'python3 /Users/ryan/Desktop/douyin_sender.py',
    verify: 'UI 顯示成功，n8n 有收到 webhook。',
    blocker: 'localhost:5678 未啟動或 webhook 路徑變更。',
  },
  {
    id: 'douyin-cookie-refresh',
    name: 'Douyin Cookie Refresh',
    category: 'Toolbox',
    description: '從 Chrome 解密 cookies 並注入 douyin-api。',
    location: '/Users/ryan/Projects/n8n/scripts/refresh_douyin_cookie.py',
    commands: ['python3 /Users/ryan/Projects/n8n/scripts/refresh_douyin_cookie.py'],
    tags: ['douyin', 'cookie', 'n8n', 'api'],
    readiness: 'Needs Service',
    useCase: '抖音流程失效時，刷新 cookie 並注入 API。',
    startup: 'python3 /Users/ryan/Projects/n8n/scripts/refresh_douyin_cookie.py',
    verify: 'log 出現注入成功，API 回 code 200。',
    blocker: 'localhost:8000 未啟動或 Chrome 未登入抖音。',
  },
]
