module.exports = {
  content: [
    './index.html',
    './login.html',
    './admin.html',
    './poster.html',
    './src/**/*.js',
  ],
  css: ['./crm.css'],
  output: './crm.purged.css',

  safelist: {
    standard: [
      'status-green', 'status-yellow', 'status-red', 'status-gray',
      'role-prospect', 'role-referral', 'role-student', 'role-agent',
      'open', 'active', 'checked', 'selected',
      'today', 'other-month',
      'connect-target', 'dragging',
    ],
    deep: [
      /^cal-/,
      /^node-/,
      /^crm-list-/,
      /^sale-/,
      /^prod-/,
      /^kpi-/,
      /^daily-/,
      /^docs-/,
      /^doc-/,
      /^student-/,
      /^stu-/,
      /^ai-/,
      /^chat-/,
      /^persona-/,
      /^quick-prompt-/,
      /^mem-/,
      /^sk-/,
      /^settings-/,
      /^theme-/,
      /^accordion/,
      /^acc-/,
      /^badge-/,
      /^ev-/,
      /^modal-/,
      /^panel-/,
      /^btn-/,
      /^field-/,
      /^cb-/,
      /^export-/,
      /^reminder-/,
      /^sdot/,
      /^act-btn/,
      /^collapse-/,
      /^quick-contact/,
    ],
    greedy: [
      /data-theme/,
      /neuo/,
    ],
  },

  keyframes: true,
  variables: true,
};
