/**
 * Auto-generated by scripts/build_survey_package.py
 * Run createLectureForm() in Google Apps Script editor.
 */
function createLectureForm() {
  var form = FormApp.create('【講座名稱】專屬課前問卷');
  form.setDescription('哈囉！歡迎報名本次的講座。\n\n為了確保這次內容能精準切中您的需求，並帶來最大的收穫，請協助花 1~2 分鐘填寫這份課前問卷。\n\n您的回覆僅供講師備課與現場交流參考，我們會妥善保管資料。');
  form.setProgressBar(true);

  form.addPageBreakItem().setTitle('第一部分：基本認識');
  form.addTextItem().setTitle('姓名 / 暱稱').setRequired(true);

  form.addMultipleChoiceItem()
    .setTitle('您的年齡區間')
    .setChoiceValues(['20-25歲', '26-30歲', '31-40歲', '41-50歲', '50歲以上'])
    .setRequired(true);

  form.addTextItem().setTitle('請問您是透過誰，或哪個管道得知本講座的呢？').setRequired(true);

  form.addTextItem().setTitle('您的星座是？（選填）').setRequired(false);

  form.addPageBreakItem().setTitle('第二部分：現況與背景');
  form.addTextItem().setTitle('您目前的職業與產業領域是？（例如：科技業/行銷企劃）').setRequired(true);

  form.addMultipleChoiceItem()
    .setTitle('您目前的總工作年資大約是？')
    .setChoiceValues(['1年以下', '1-3年', '4-7年', '8-10年', '10年以上'])
    .setRequired(true);

  form.addCheckboxItem()
    .setTitle('關於財務與理財現況，您目前符合以下哪些描述呢？（可複選）')
    .setChoiceValues(['有固定薪資收入（薪轉）', '有投資理財習慣（股票、基金、虛擬貨幣等）', '已為自己規劃商業保險', '名下有房地產（或家人有）', '有使用信用卡消費的習慣', '有貸款或負債正在償還中'])
    .setRequired(true);

  form.addPageBreakItem().setTitle('第三部分：價值觀與痛點');
  var checkboxValidation = FormApp.createCheckboxValidation()
    .requireSelectAtMost(2)
    .setHelpText('請最多勾選 2 項')
    .build();
  form.addCheckboxItem()
    .setTitle('現階段的人生中，您覺得以下哪兩項對您來說最重要？（請勾選 2 項）')
    .setChoiceValues(['家庭 (Family)', '工作與事業 (Occupation)', '休閒興趣 (Recreation)', '財務狀況 (Money)', '個人夢想 (Dream)', '身體健康 (Health)'])
    .setValidation(checkboxValidation)
    .setRequired(true);

  form.addParagraphTextItem().setTitle('目前生活中，您遇到最大的痛點/煩惱，或最想達成的夢想是什麼？').setRequired(true);

  form.addParagraphTextItem().setTitle('這次報名本講座，主要是對什麼主題或能力最感興趣？').setRequired(true);

  form.addPageBreakItem().setTitle('第四部分：期待與決策');
  form.addMultipleChoiceItem()
    .setTitle('若未來有進修、投資或重大花費的計畫，您通常是如何做決定的？')
    .setChoiceValues(['我可以自己做主', '習慣先與家人或伴侶討論'])
    .setRequired(true);

  form.addMultipleChoiceItem()
    .setTitle('關於後續延伸學習的學費方案，您的了解程度是？')
    .setChoiceValues(['已有初步了解，想聽完講座後評估是否投入', '尚不清楚，希望在講座中了解相關資訊'])
    .setRequired(true);

  form.addParagraphTextItem().setTitle('最後，對於本次講座，您有什麼最想問講師的問題嗎？（選填）').setRequired(false);

  form.setConfirmationMessage('感謝您的填寫！我們已經收到您的回覆。\n請記得將講座時間加入行事曆，我們到時候見。\n若有任何問題，歡迎聯繫 [請填入聯絡窗口/LINE官方帳號]。');
  Logger.log('Published URL: ' + form.getPublishedUrl());
  Logger.log('Edit URL: ' + form.getEditUrl());
}
